### ISSUE TITLE
Add link to website to top-right of github repo page.

### ISSUE THREAD

**Issue by epost** [spacchetti/starsuit#4]
In addition to having the https://spacchetti.github.io/starsuit/ link in the readme, it might be nice to put it in the 'website' field in the top-right corner of https://github.com/spacchetti/starsuit.

**Comment by klntsky** [comment]
Hi, yes. Apparently, it's something only admins can do.

CC @f-f

**Comment by f-f** [comment]
@klntsky I added the link and added you as admin :slightly_smiling_face:

**Comment by epost** [comment]
Thanks folks! :)

**Comment by f-f** [comment]
@epost you're welcome :slightly_smiling_face:
